In [3]:
import numpy as np

## 이산화 사용 이유

수치 특성을 범주형처럼 다룰 때 유용한 전략이다. 예를 들어 18세와 19세의 소비 습관은 차이가 매우 작지만 19세와 20세 사이는 차이가 클 수 있다. 20세부터는 성년이어서 술을 살 수 있기 때문이다.

## 특성을 둘로 나누기

- sklearn.preprocessing.Binarizer
- numpy.digitize(x, bins=[])

In [16]:
from sklearn.preprocessing import Binarizer

age = np.array([[6],
                [12],
                [20],
                [36],
                [65]])

bi = Binarizer(threshold=18)
print(bi.fit_transform(age))
bi2 = np.digitize(age, bins=[20])
print('\n', bi2)

[[0]
 [0]
 [1]
 [1]
 [1]]

 [[0]
 [0]
 [1]
 [1]
 [1]]


## 특성을 여러 임곗값에 따라 나누기

- [numpy.digitize](https://numpy.org/doc/stable/reference/generated/numpy.digitize.html){target=_blank}
- numpy.digitize(x, bins, right=False)
- bins = 리스트. 요소는 구분 기준으로 사용되는 경곗값(경곗값은 포함하지 않음) 
- eg. [20, 30, 64] -> [ , 20), [20, 30), [30, 64), [64, ) '['는 포함 '('는 포함하지 않음
- right=True : 경곗값을 포함

In [13]:
print(age.flatten())
np.digitize(age, bins=[20, 36, 64]).flatten()

[ 6 12 20 36 65]


array([0, 0, 1, 2, 3])

In [14]:
np.digitize(age, bins=[20, 36, 64], right=True).flatten()

array([0, 0, 0, 1, 3])

## KBinsDiscretizer

- sklearn.preprocessing.KBinsDiscretizer(n_bins=5, encode='onehot', strategy='quantile')
- encode='ordinal/onehot/onehot-dense' : 원핫 인코딩된 희소 행렬 반환. 'onehot-dense'는 원핫 인코딩된 밀집행렬 반환.
- strategy='quantile/uniform/kmeans' : quantile-각 구간의 샘플 개수 비슷, uniform-구간 폭 동일
- 구간 경계값은 bin_edges_ 속성

In [18]:
from sklearn.preprocessing import KBinsDiscretizer

kb = KBinsDiscretizer(4, encode='ordinal', strategy='uniform')
print(kb.fit_transform(age))
print(kb.bin_edges_)

[[0.]
 [0.]
 [0.]
 [2.]
 [3.]]
[array([ 6.  , 20.75, 35.5 , 50.25, 65.  ])]
