In [ ]:
---
title: "배열 크기 바꾸기"
date: 2022/11/15
updated: last-modified
format: 
  html:
    code-fold: false
---

## reshape와 flatten 차이

- reshape : 얕은 복사
- flatten : 깊은 복사

In [ ]:
vetor_reshaped = matrix.reshape(1, -1)
print('reshape:\n', vetor_reshaped)
matrix[0][0] = 100
print('원본 변경 사항이 반영됨:\n', vetor_reshaped)

vetor_flattened = matrix.flatten()
print('flattened', vetor_flattened)
matrix[0][0] = 500
print('원본 변경 사항이 반영되지 않음:\n', vetor_flattened)

reshape:
 [[500  12  13  14  15  16  17  18  19]]
원본 변경 사항이 반영됨:
 [[100  12  13  14  15  16  17  18  19]]
flattened [100  12  13  14  15  16  17  18  19]
원본 변경 사항이 반영되지 않음:
 [100  12  13  14  15  16  17  18  19]
