In [1]:
import numpy as np

#### 넘파이 배열의 각 원소에서 행의 평균을 빼기

keepdims=True -> 원본 배열의 차원과 동일한 결과를 만듦

In [ ]:
matrix = np.arange(11, 20).reshape(3,3)
print('배열:\n', matrix)
print('행별 평균:\n', np.mean(matrix, axis=1, keepdims=True))
print('배열의 각 원소에서 행별 평균 빼기:\n', matrix - np.mean(matrix, axis=1, keepdims=True))


배열:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
행별 평균:
 [[12.]
 [15.]
 [18.]]
배열의 각 원소에서 행별 평균 빼기:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 분산과 표준편차에 자유도 고려하기

ddof=n

In [ ]:
print('자유도를 지정하지 않은 분산(기본값 ddof=0): ', np.var(matrix))
print('자유도 1을 지정한 분산: ', np.var(matrix, ddof=1))

자유도를 지정하지 않은 분산(기본값 ddof=0):  6.666666666666667
자유도 1을 지정한 분산:  7.5


## 참고

- 파이썬을 활용한 머신러닝 쿡북(크리스 알본 저, 박해선 역)